[project]
name = 'oja-art'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.oja-art]
path = 'contracts/oja-art.clar'
clarity_version = 2
epoch = 2.5

[contracts.oja-art-traits]
path = 'contracts/traits/oja-art-traits.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
